#define AUTHOR_HEADER AYAS_OUKACHE
#define FILE_HEADER AYAS_FILE
#define DATE_HEADER 2_03_2026_16_46
#define LOCATION_HEADER MACBOOKAIR_COCOPAR_VISUALCODE
#define RWA_LOCATION ECS_72650_FR_EUR
#define INTENT CURE_ALZHEIMER_DISEASE
#define INTENT_2 BUILD_A_DANCE_CENTER__DXNC_

#ifndef PROFIL_HEADER
#define PROFIL_HEADER
#endif
